name: Deploy to Amazon Lambda

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

env:
  COGNITO_POOL_ID: ${{ secrets.COGNITO_POOL_ID }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    environment: production    

    steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::014552381854:role/OIDC_github
        aws-region: eu-central-1
        # profile name vidvely

    - name: Deploy to AWS Lambda
      run: |
        npm install
        npm run deploy:dev